### ISSUE TITLE
ES syncer jobs in prod mode

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#285]
Not sure how the ES syncer background jobs should be run in production mode (for instance for the demo).

https://github.com/c2corg/v6_api#run-the-application says that one should type

```
make -f config/$USER run-background-jobs
make -f config/$USER run-syncer
```

but can we really use them in prod mode (while the API is run through apache/WSGI, not with paster and "make serve" as in the dev mode)? If yes how? In a screen?

By the way I notice that those scripts seem to rely on `development.ini` using for instance

```
.build/venv/bin/python c2corg_api/scripts/jobs/scheduler.py development.ini
```

**Comment by tsauerwein** [comment]
You can use the targets `run-background-jobs-prod` and `run-syncher-prod`, which use the `production.ini`. See https://github.com/c2corg/v6_api#run-the-application

For now, you can run them in a screen (e.g. with tmux), but we have to figure out with @mfournier how to run the scripts in the Docker environment.

**Comment by asaunier** [comment]
> For now, you can run them in a screen (e.g. with tmux), but we have to figure out with @mfournier how to run the scripts in the Docker environment.

@tsauerwein @mfournier @arnaud-morvan 
As a solution been found? Are those scripts running in the beta demo?

**Comment by asaunier** [comment]
> As a solution been found? Are those scripts running in the beta demo?

Could someone answer the questions please? Yes? No?

**Comment by arnaud-morvan** [comment]
IMHO we should add a service for each job in the composition.
We will get 3 containers running the same v6_api image with different commands.
``docker-compose up -d`` will start them as api, ui and images.
And we should use the ``restart: always`` option.
@mfournier : any remarks

**Comment by arnaud-morvan** [comment]
I'll give it a try on the demov6 server ... this should not have any effect on the running services.

**Comment by arnaud-morvan** [comment]
This is already the case on demov6:
```
  syncer:
    image: 'c2corg/v6_api:latest'
    restart: always
    links:
      - 'postgresql'
      - 'elasticsearch'
      - 'syslog'
    environment:
      db_host: postgresql
      elasticsearch_host: elasticsearch
    command: python ./c2corg_api/scripts/es/syncer.py production.ini
  
  scheduler:
    image: 'c2corg/v6_api:latest'
    restart: always
    links:
      - 'postgresql'
      - 'syslog'
    environment:
      db_host: postgresql
    command: python ./c2corg_api/scripts/jobs/scheduler.py production.ini
```
